import { NextRequest, NextResponse } from "next/server";
import { storage } from "@/lib/storage";
import { adminSchema } from "@shared/schema";

export async function GET() {
    try {
        const admins = await storage.getAdmins();
        return NextResponse.json(admins);
    } catch (error) {
        console.error("Error fetching admins:", error);
        return NextResponse.json({ error: "Failed to fetch admins" }, { status: 500 });
    }
}

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        // Since id is auto-generated by the database/storage, we omit it from validation if present in body
        // or just validate the fields we expect.
        // adminSchema includes ID which is required for the Type but not for creation if generated.
        // Let's assume we validate strict shape minus ID.
        const parseResult = adminSchema.omit({ id: true }).safeParse(body);

        if (!parseResult.success) {
            return NextResponse.json({ error: "Invalid admin data", details: parseResult.error }, { status: 400 });
        }

        const newAdmin = await storage.createAdmin(parseResult.data);
        return NextResponse.json(newAdmin, { status: 201 });
    } catch (error) {
        console.error("Error creating admin:", error);
        return NextResponse.json({ error: "Failed to create admin" }, { status: 500 });
    }
}
